server {

    server_name rusalts.ru www.rusalts.ru;

    root /var/www/rusalts.ru/html;
    index index.html;

    client_max_body_size 10m;

    location ^~ /.well-known/acme-challenge/ {
        allow all;
        default_type "text/plain";
    }

    location /widget {
        proxy_pass http://127.0.0.1:8000;
        include proxy_params;
        proxy_http_version 1.1;
    }

    location /api {
        proxy_pass http://127.0.0.1:8000;
        include proxy_params;
        proxy_http_version 1.1;
    }

    location /static {
        proxy_pass http://127.0.0.1:8000;
        include proxy_params;
        proxy_http_version 1.1;
    }

    location = /health {
        proxy_pass http://127.0.0.1:8000;
        include proxy_params;
    }

    location /docs {
        proxy_pass http://127.0.0.1:8000;
        include proxy_params;
    }

    location /openapi.json {
        proxy_pass http://127.0.0.1:8000;
        include proxy_params;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    listen [::]:443 ssl ipv6only=on;
    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/rusalts.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/rusalts.ru/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

}

server {
    if ($host = rusalts.ru) {
        return 301 https://$host$request_uri;
    }

    listen 80;
    listen [::]:80;

    server_name rusalts.ru www.rusalts.ru;
    return 404;

}
